name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t node-app:latest .

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: node-app:latest
        severity: HIGH,CRITICAL
        exit-code: 1
        format: table
        output: trivy.txt

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy.txt
